
language: java
jdk:
  - oraclejdk11

jobs:
  include:
    - os:
        - linux
      script:
        - gradle check --info --stacktrace

    - os:
        - osx
      script:
        - ./gradlew check --info --stacktrace

    - os:
        - linux
      install:
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      script:
        - mvn clean test

    - os:
        - osx
      install:
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      script:
        - mvn clean test

    - os:
        - linux
        script:
          - gradle shadowJar
          - gradle distZip
          - gradle distTar
          - gradle shadowDistZip
          - gradle shadowDistTar
