
language: java
jdk:
  - oraclejdk11

jobs:
  include:
    - os:
        - linux
      script:
        - gradle check --info --stacktrace

    - os:
        - osx
      script:
        - gradle check --info --stacktrace

    - os:
        - linux
      script:
        - mvn clean test

    - os:
        - osx
      script:
        - mvn clean test
